### ISSUE TITLE
apiKey header should ignore case?

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1057]
I'm trying to make an API request from my browser to CEDAR. I've added Modify Headers to chrome and set my apiKey to the correct value, but I'm still getting rejection. (Curl is working OK.)  

It seems that Modify Header changes apiKey to apikey (all lower case), which in Curl is enough to cause the key to be rejected.

Random searching found this:
```
Hey @Robpizza, the HTTP spec does define header fields as case insensitive - so servers should be case insensitive as well.

Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.
```
and

```
HTTP header names are case-insensitive, according to RFC 2616: ... Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. (Field values may or may not be case-sensitive.)
```

Can I call this a bug in our server? It keeps me from demonstrating in my browser (well, found a workaround for that), and may surprise other users as well.

**Comment by egyedia** [comment]
It looks like this issue is closed.
I just want to add to it a small information:
The actual header name here is "Authorization:" . That definitely should be handled in a case-insensitive way, and I am double-checking the code now to make sure that that is true.
BUT
apiKey is part of the header value. So there is no requirement that that should be case-insensitive. But I will add that case-insensitive check just for convenience as well.

**Comment by egyedia** [comment]
As I mentioned before, the header in question is Authorization. I double-checked, and that is case-insensitive, since we are using the HttpServletRequest implementation, which implements the standard correctly.
The "apiKey xyzabc" is the value of that header, and as such, it should not be case-insensitive. But for convenience, I added the case-insensitive behavior. This also applies to the "Bearer " value.
