### ISSUE TITLE
Template/element instructions

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#1064]
To reflect caDSR requirements, provide way to add template-level and element-level instructions for users.

**Comment by marcosmro** [comment]
I've enhanced Template Designer's header section to include a collapsible area with two additional fields: Header and Footer, so that the user can enter header and footer information, respectively. (see Screenshot 1). 

The footer and header information is shown when entering metadata using the template (see Screenshot 2). These fields are available both for templates and elements.

Screenshot 1:
![Screen Shot 2020-08-10 at 11 47 48 AM](https://user-images.githubusercontent.com/7634440/89819083-b1a33400-daff-11ea-8fa7-80fdd6842ec6.png)

Screenshot 2:
![Screen Shot 2020-08-10 at 11 48 02 AM](https://user-images.githubusercontent.com/7634440/89819106-b5cf5180-daff-11ea-80d1-b989321eb951.png)
