### ISSUE TITLE
Category for NHLBI not seeing all CDEs

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1121]
When opening NHLBI category in CEDAR, 2429 CDEs are shown. When opening that category in caDSR, they see over 5000 CDEs. 

They believe they are also looking at released CDES, only most recent version, and 'owned by' still shows over 5000 CDEs (but their default is 'used by', which is a slightly larger number).

Not clear where this problem lies (could be download set, or CEDAR processing).

**Comment by marcosmro** [comment]
I've been looking into this issue, and the number of CDEs in CEDAR is correct. The CDE Browser (https://cdebrowser.nci.nih.gov/) shows a higher number of RELEASED CDEs for the NHLBI context (as well as for other contexts) because it takes into account the CDEs under two subcategories: "Classifications" and "Protocol Forms" (see the screenshot attached). CEDAR categories are generated based on the "Classifications." When checking the number of CDEs in the different classifications under the "Classifications" branch (BRIDGE, Disease Relapse, Family Blood Pressure Program, etc.), the counts are correct.

![Screen Shot 2021-04-22 at 10 37 29 AM](https://user-images.githubusercontent.com/7634440/115761038-bf7bab00-a356-11eb-82a8-8b55fe19ceeb.png)
