### ISSUE TITLE
Get template-instances does't return values

### ISSUE THREAD

**Issue by akoleti** [metadatacenter/cedar-project#211]
It doesn't work if followed the documentation @ "https://resource.metadatacenter.net/#!/template-instances/GET_controllers_TemplateInstanceController_findTemplateInstance" curl -X GET --header  'Authorization: apiKey 75b7516a-7d7c-4cca-bc56-95e91d91cb28' 'https://resource.metadatacenter.net/template-instances/510d3845-fbd6-4686-a008-774d6287d706' 

but works using this
 curl -X GET --header  'Authorization: apiKey 75b7516a-7d7c-4cca-bc56-95e91d91cb28' 'https://repo.metadatacenter.net/template-instances/510d3845-fbd6-4686-a008-774d6287d706'

**Comment by egyedia** [comment]
You need to provide a URLEncoded full URI as the identifier:

https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-REST-APIs

Example: 
curl -H "Content-Type: application/json" -H "Authorization: apiKey xxx" \
-X GET --header 'Accept: application/json' 'https://resource.metadatacenter.net/template-instances/https%3A%2F%2Frepo.metadatacenter.net%2Ftemplate-instances%2Fc1199f96-dbd3-4476-8141-1f1fb13e1bca'

There is also a bug in our code, we are returning HTTP 500 instead of 404. We will fix that.
