### ISSUE TITLE
Weird dialog message when attempting to delete a folder

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#370]
The following message appears when an integration test is deleting a folder:

> Folder not found! Please use the UI elements to navigate to an existing folder!

However, the folder **was selected through and was visible in the UI**, after a search for that specific folder name. What's a user supposed to do or learn from this message?

**Comment by rsgoncalves** [comment]
Took a screencast of a run of update-name-spec.js: https://youtu.be/CMRjwS4w5nQ. Notice that the above occurs shortly after minute 1:00, but unfortunately there isn't a toasty notification to click on for more details. Outside of the test execution, I have no problem deleting the folder in question.

**Comment by egyedia** [comment]
Yes, the toasty is hidden since this is a kind of an error (folderNotFound) which we are expecting.
Not in this case, but in general. So if the error key is folderNotFound, we are showing a meaningful error message, and not the scary stack trace.
But the stack trace should be there, in the REST call, in the Network Panel of the browser.
So is this reproducible if I run the update-name-spec.js alone?

**Comment by rsgoncalves** [comment]
This should be reproducible using branch `testing/permissions`, and running that spec alone. The failure should occur on the (second to last) test: 'should delete the test resources created by Test User 1'.
