### ISSUE TITLE
Error connecting to BioPortal messages

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#415]
OK, this is happening pretty often. I select the values tab, hit Search, and enter Sunnyvale into the search string. This brings up a GAZ entry; I click on it, click on Ontology tab, and click on ADD.

At this point the ontology appears to be added, but I get anywhere from 5 to 10 "Error connecting to BioPortal, please try later" messages. I am imagining it is retrying, and succeeds, but only after the error messages are issued.

If that is correct, then those error messages probably should not be issued if the connection is going to be retried anyway. Certainly getting 5-10 at once is a bit of overkill.

**Comment by marcosmro** [comment]
I have applied the following fixes:
1) Limited the number of errors that can be shown on the screen to 1, so that 'red boxes' are not accumulated. Previous limit was 10. This fix has already been applied to staging.
2) Toned down the BioPortal error messages by showing them as warnings, in yellowish color instead of red. 
Additionally, we will exhaustively monitor the BioPortal endpoints used by CEDAR using StatusCake (see https://github.com/metadatacenter/cedar-project/issues/417).
