### ISSUE TITLE
GET requests without authorization?

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#443]
(From Douglas Russell)
I would like to take advantage of community maintained templates and template components deposited in CEDAR, but this is difficult because it it only seems possible to access the REST API with an API key. It would be really great to lift this restriction to allow GET requests without authorization so that client side tools can access the repository. Any chance of that?

(His follow-on, "In the meantime, would be possible and admissible to have an API key with limited privileges to be used in my web based tool (and thus made public)?", is request #442)

**Comment by martinjoconnor** [comment]
The user of the client side tool can generate an API key easily. This key also allows us to track who is using the system.

One of the problems we have with Protege, BioPortal etc. is that we have only the vaguest idea who is using the system - which is a problem when writing grants etc.

**Comment by martinjoconnor** [comment]
Making the Schema.org work accessible without an API key (which we would have to to get indexes) will allow people to find stuff on CEDAR.

If they want to access low level content via our REST APIs asking them to get an API key is not a high bar and benefits us considerable. (Also makes debugging potentially easier because we can identify sources of traffic that causes issues.)

**Comment by dpwrussell** [comment]
I can certainly understand that funders want statistics on usage and we have had to deal with this ourselves many times.

I completely agree that it is not unreasonable to ask users who are individually using your API to sign up for an account, but in this case, I am deploying my application as a plugin into a larger piece of software that is installed as a repository in thousands of locations around the globe, each of those installations with many users. Only a subset of those will ever use my application and for those that do I would expect the majority to never write to CEDAR, but do a lot of reading. I know from experience that signup is a major barrier to adoption so I would like to avoid requiring that of these users.

A potential flipside of this is that if I have to proxy requests through my backend using a single secret key to make requests to CEDAR then this would actually obfuscate your actual usage. Also, later on I would like to add the capability for users to configure a personal CEDAR account so that they could access restricted templates and/or write templates back and I can't do that through the proxy, so a public interface with options to use a key would make a lot of sense for this use case.

Obviously the question of public or not is something which you have to resolve internally, but my experience with this is that signup is a huge barrier to adoption, especially in integration cases like this.

**Comment by martinjoconnor** [comment]
Now addressed by metadatacenter/cedar-project#946
