### ISSUE TITLE
BioPortal key handling for CEDAR deployments

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#446]
Strategy for handling BioPortal keys in CEDAR deployments.

**Comment by graybeal** [comment]
Please describe what you're hoping I'll deliver.

**Comment by martinjoconnor** [comment]
When we distribute a Docker image we need to distribute a BioPortal API key with it.

Simple approach is to create a CEDAR Docker user in BioPortal and use the key for that user. This should work out of the box. They key is pretty much public at this point.

Is this ok from the BioPortal point of view. Any other suggestions?

**Comment by graybeal** [comment]
Why is the key "pretty much public at this point"? Oh, I imagine you are using one key for all CEDAR Docker users?  This will not be acceptable, because if any one user is abusive, all users will have to get new keys. And also we use the keys to throttle requests to 15Hz. (This will likely be a problem with larger individual CEDAR systems.)

It also relates to the fact we definitely want to keep track of the different CEDAR installations making requests, and the people who have made them, so we can contact them to address issues as needed (e.g., if their system is submitting broken requests). 

So, each CEDAR Docker user should get a unique key. This can be done either (a) as part of the packaging process, pre-requesting specific accounts, or (b) by the Docker recipient applying for the account directly to BioPortal and then installing the key in their distribution. Quickie analysis: (a) is cleaner, more uniform, makes it easy to tag BioPortal accounts as CEDAR/non-CEDAR, and to know which CEDAR user is on which BIoPortal account. (b) is easier for us to manage, lets users more easily name their account (not that that matters), more anonymous. 

Path (a) incidentally could enable us to track which CEDAR Docker users actually get to the stage of using the system. Because it gives us a way to associate the key to the original requester.

**Comment by martinjoconnor** [comment]
Forcing each Docker user to get a BioPortal key is fine for me, though it does increase adoption friction slightly.

I don't see how it can be done as part of the packaging process without significant work.

**Comment by graybeal** [comment]
I guess it would require registration for access to Docker image (a bit unusual, but what BioPortal effectively does), the auto-creation of BioPortal users based on that user's info (not too hard), and ideally the coupling of the obtained API key to the appropriate configuration file in the Docker image (or the direct delivery of it to the user, who then configures the system). 

I don't see how we can manage "CEDAR load" on BioPortal without knowing which API keys are CEDAR deployments. Call me crazy, but I think CEDAR has the potential to contribute a lot of usage. We also can't tell how many CEDAR instances are in the wild making use of BioPortal, and how much use they are making. (And it's just good operational practice, to know the scope of system interactions.)

Arguably, that last paragraph of needs could be (better?) addressed by getting reports directly from the CEDAR software. But that also is a fair bit of development, potentially more than tracking through BioPortal.

**Comment by martinjoconnor** [comment]
Registration for access to Docker images is absolutely horrible IMHO - and is very much against the open source ethos. 

Auto-creation of a BioPortal user is tricky, nasty code with many error cases. 

Easiest solution is to ask user to register on BioPortal and get a key. What would be nice (but will require work) is that CEDAR works without the key and they user only sees the lack when they try to use BioPortal features. They can then go get one and give it to Docker. System does not work that way at the moment though.

**Comment by martinjoconnor** [comment]
Docker deployment currently requires user get a BioPortal key, which should suffice for the moment.

See also:

https://github.com/metadatacenter/cedar-terminology-server/issues/29
