### ISSUE TITLE
Search for number does not complete

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#449]
In my account, if I enter a search term like 4732751, the red bar goes zipping across about 2/3 of the way, then it gets slower, and slower, until I can't tell if it's moving at all. Search doesn't seem to finish, in several minutes anyway.

From cedar-admin account, search just whizzes right through.

**Comment by graybeal** [comment]
<img width="1401" alt="screen shot 2017-05-07 at 8 47 09 pm" src="https://cloud.githubusercontent.com/assets/1266896/25786655/cd9c8d8a-3366-11e7-833f-00dbdcc95c83.png">

**Comment by marcosmro** [comment]
This issue can be reproduced by searching for the same term two or more consecutive times. If the search query does not change, the system will not trigger a new search but it still will wait for a search response indefinitely. 

If fixed it by adding a timestamp parameter to the search url, so that consecutive searches with the same term will always generate different urls and therefore the system will trigger new queries.
