### ISSUE TITLE
Default values re-appear in Template Editor

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#507]
In Template Editor text fields (for example), all the fields have some default text ("Untitled", "Description", "Enter Default Value"). The first two won't erase -- if you erase all the characters it pops back up with the default text. Over and over. 

The third behaves in the way I'd like the first two to behave. The default view text can be a little more wordy, If I click on the field, it's a safe bet I want to start from scratch. 

We can still use Untitled as the actual default value for the name if you want, but only use it if the person has emptied the field, don't actually show it at the beginning. (Actual default value for description field should be empty.)

**Comment by willrett** [comment]
All input fields can have "placeholder" text which is shown in a different color and moves out of the way when the user enters text.  When a new field is created, all three input fields show only the placeholder text.  If the user saves the template or just selects another field, "Untitled" is used as the default title because a title is required, but the other two fields are left blank.

**Comment by graybeal** [comment]
Is this being closed without changes?  I don't think this explanation addresses the issue.

**Comment by willrett** [comment]
Changes were made in another issue.  Description and default value behave differently than title.  The title must be set to the default value at some point.  The other fields may remain empty.

**Comment by graybeal** [comment]
Also confirmed that "Default" does not instantly appear upon clearing the name, but is added later.
