### ISSUE TITLE
when template cannot be edited because it's in use, offer to make a copy or to show where the template is being used

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#609]
When template creator tries to edit a template and the template has already been used to create metadata, user gets error “you can’t modify this template because it’s in use”.

At this point, offer to make a copy of the template. Or offer to show user the metadata instances that use the template.

In practice, the template editor will make a template, then want to try it out (or ask someone else to try it out), and then go back and edit it further. Now that you stop the user from editing a template once it has been used for metadata, it's not possible to work iteratively like this.

If you do implement https://github.com/metadatacenter/cedar-template-editor/issues/605, that would allow the template creator to work in this iterative way.

(Note these comments do not take into account versioning of templates, see https://github.com/metadatacenter/cedar-project/issues/608)

**Comment by graybeal** [comment]
I have this exact problem with this change. For many tasks and tests, I work iteratively in a single file, and care little if I've messed up a previous instance (and know what kind of changes are likely to mess up a previous instance). Now working with existing templates is harder and messier.

I know it is all but impossible to manage the disconnect between changing templates and existing instances, at least until we have versions or a more refined approach to updating instances. But a message saying "These instances use your existing template. / Since all of them were created by use, would you like to delete them? / " would make it a lot less painful.

**Comment by willrett** [comment]
Fix until versioning is ready: turn on a warning and let users edit.
Same for #654
