### ISSUE TITLE
Creating a controlled term field results in validation error

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#612]
On staging, create a template with one textfield, and set the values of the field as the branch of "disease" from EFO.  Validation errors result on save.

**Comment by johardi** [comment]
It seems the property `@required` is missing when the editor produces the template JSON. Further checking this issue will only happen when there is a value constraint (e.g., from ontology, branches, etc.)

**Comment by martinjoconnor** [comment]
See also #603

**Comment by martinjoconnor** [comment]
See also https://github.com/metadatacenter/cedar-project/issues/621

**Comment by marcosmro** [comment]
This is the expected behavior. Fields that have been constrained to ontology terms store their values (i.e., the selected ontology term) in the @id field. Given that the value of @id cannot be represented as null or empty (i.e., "disease":{"@id":null} is invalid), when the value is empty the editor generates an empty object for those fields (e.g. "disease" : {}). As a consequence, we don't need to require anything and the 'required' field is not needed. For fields that don't have any value constraints the behavior is different because the value is stored in the @value field, which can be empty or null (e.g., "disease":{"@value":null} is valid)
@johardi: I think that the validator needs to be updated to accept the missing 'required' when the field has been constrained to ontology terms.

**Comment by martinjoconnor** [comment]
See https://github.com/metadatacenter/cedar-model-validation-library/issues/68
