### ISSUE TITLE
an element should not look like it is subordinate to the field above it

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#627]
In Metadata Editor, the dash-triangle to the left of elements (used for expanding/collapsing) makes the name of the element be indented farther than the name of a "regular" field, so if you have a regular field followed by an element, it looks like the element somehow belongs within the field above. In the attached screenshot, for example, it looks as if "Form Genre" is a heading of some kind, and the "Preferred title", "Title information", and "Activity" are fields within that "Form Genre" section.

**Comment by michelleif** [comment]
![fieldsvselements.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46ee9d9f2f8690bf9cecb346a958fe803a046b313916ac217586f76ae5002e570c594ead41095616aef9dd28a7b53c708e5d0ce5873e4d68d47f40f2ecdd42e64bef62994597b7bb804dc5e93f25ef8c8947361b0d1b9bb2.png)

**Comment by willrett** [comment]
The fields do not look subordinate to preceding elements.  The fields and elements are all shown at the same level in the tree.

**Comment by graybeal** [comment]
I beg to differ. To my eyes, Preferred title, Title information, and Activity are clearly (visually) subordinate to the Form Genre element. Possibly you have internalized the meaning of the right arrows so that you interpret the visuals differently, but my outlining experience uses both leading edge of the characters, and the existence of sub-bullets (which is what the arrows look like), to determine that the 3 attributes mentioned are indented hierarchically a level below the Form Genre topic.

**Comment by graybeal** [comment]
I think this issue has been addressed by recent improvements to the instance layout.
![Screen Shot 2018-05-08 at 12.59.58 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454fb6b7191a379ed0c2e58415a46bc21254d58eeb9cb74fce36f34985619e8d73e5974c73d40a5ead01feb02bb238b4f81b7bb821a93fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e44555ad153767e176316e0a.png)
