### ISSUE TITLE
Open port 443 and establish subdomains for backup machines

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#76]
Need to open SSL port 443 for cedr-dev-app-{06,07,08}.stanford.edu and establish standard CEDAR subdomains (auth, cedar, template, repo, schema, terminology, user, valuerecommender, resource, folder) so that we can generate SSL certificates.

Needed for task #50. Would be good to have by Friday 5th August.

**Comment by graybeal** [comment]
Sorry, neglected to get this assigned this week. Will have Graham do when he returns Monday.

**Comment by graybeal** [comment]
Reference BMIR tracking issue https://jira.bmir.stanford.edu/browse/BMIRIT-298

**Comment by gjmf** [comment]
Per our in-person conversation today, the restored host is available at cedar-restore.stanford.edu.  Individual subdomains are configured as $SUBDOMAIN.restore.metadatacenter.org.  TCP 443 is open.  SSH logins work.

luna-laptop:~ grahamfreeman$ for SUBDOMAINS in auth cedar template repo schema terminology user valuerecommender resource folder; do host $SUBDOMAINS.restore.metadatacenter.org; done
auth.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
cedar.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
template.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
repo.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
schema.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
terminology.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
user.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
valuerecommender.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
resource.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
folder.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu.
cedar-restore.stanford.edu has address 171.67.213.10
luna-laptop:~ grahamfreeman$ nmap -sT -p443 cedar-restore.stanford.edu

Starting Nmap 7.12 ( https://nmap.org ) at 2016-08-08 18:02 PDT
Nmap scan report for cedar-restore.stanford.edu (171.67.213.10)
Host is up (0.0016s latency).
PORT    STATE SERVICE
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds
luna-laptop:~ grahamfreeman$ ssh cedar-restore.stanford.edu
Last login: Mon Aug  8 18:01:45 2016 from luna-laptop.stanford.edu

Stanford University Biomedical Informatics Research

-----------------------------------------------------------------------------
 This system is for authorized users only and you are expected to comply
 with all Stanford computing, network and research policies.  For more info,
 see https://adminguide.stanford.edu/chapter-6/subchapter-2/policy-6-2-1 
-----------------------------------------------------------------------------

Please report any problems to "bmir-it-team@lists.stanford.edu".

-bash-4.1$ exit
logout
Connection to cedar-restore.stanford.edu closed.
luna-laptop:~ grahamfreeman$

**Comment by gjmf** [comment]
It turns out TCP 443 may only be open locally within BMIR's internal network (& VPN).  I'll fix that.

**Comment by gjmf** [comment]
The solution to opening TCP 443 issue was to change the way we use the campus-wide firewall for this host.  It's solved now, pending some NetDB updates and DNS cache expirations.

You can clear your local Mac resolver by following these instructions:  https://support.apple.com/en-us/HT202516

You'll see the current/correct results once your DNS lookups ultimately resolve to IP 171.67.213.55.

**Comment by gjmf** [comment]
Please keep in mind that this version of the site will now be accessible to Google and other search engines.  I recommend adding appropriately restrictive robots.txt entries to avoid unwanted search results.

**Comment by martinjoconnor** [comment]
I a bit confused by the naming. This is sort of hurting my head in terms of managing certificates with subdomains: 

    schema.restore.metadatacenter.org is an alias for cedar-restore.stanford.edu

 Our current approach is to have

    {auth, cedar, repo, ...}.<hostname> 

e.g., 

    repo.metadatacenter.net
    repo.staging.metadatacenter.net

So I would expect

    {auth, cedar, repo, ...}.cedar-restore.stanford.edu

This would give us a consistent scheme for managing our certificates without thinking about aliases etc. In fact, I'd prefer not to have to think about aliases if possible - beyond our staging and production machines. 

Would it be possible to (eventually) have:

{auth, cedar, repo, ...}.cedar-restore.stanford.edu
{auth, cedar, repo, ...}.cedar-staging.stanford.edu # alias for staging.metadatcenter.net
{auth, cedar, repo, ...}.cedar-production.stanford.edu  # alias for metadatcenter.net
{auth, cedar, repo, ...}.cedar-test.stanford.edu
{auth, cedar, repo, ...}.cedar-dev1.stanford.edu
{auth, cedar, repo, ...}.cedar-dev2.stanford.edu

These would all be externally resolvable with port 443 open so that we can do all the necessary SSL certificate stuff. 

I know that these machines can be aliased in many way internally but it  would be great for us not to have to think about those aliases (and not even necessarily know about them).

**Comment by gjmf** [comment]
Hi, Martin,

You can safely ignore the details of how the DNS resolution works, and use the following consistent FQDNs as-is:

auth.restore.metadatacenter.org
cedar.restore.metadatacenter.org
template.restore.metadatacenter.org
repo.restore.metadatacenter.org
schema.restore.metadatacenter.org
terminology.restore.metadatacenter.org
user.restore.metadatacenter.org
valuerecommender.restore.metadatacenter.org
resource.restore.metadatacenter.org
folder.restore.metadatacenter.org

Best to SSH to cedar-restore.stanford.edu, but if it makes your scripting/etc. easier you can SSH to restore.metdatacenter.org instead.

In case you prefer a different method of DNS resolution (A records instead of CNAMEs), you can use the following:

auth.restore.metadatacenter.net
cedar.restore.metadatacenter.net
template.restore.metadatacenter.net
repo.restore.metadatacenter.net
schema.restore.metadatacenter.net
terminology.restore.metadatacenter.net
user.restore.metadatacenter.net
valuerecommender.restore.metadatacenter.net
resource.restore.metadatacenter.net
folder.restore.metadatacenter.net

We can certainly implement the "eventually" portion of your request as a separate project.

**Comment by graybeal** [comment]
I think it isn't about the 'how', it's about the what, with two pieces: (1) How do we test the restored instance? (2) How do we mint and manage domain names going forward?

Re (1), I think all the domain names *.restore.metadatacenter.net should work just fine (I will verify this with Graham), and Martin should use them for generating SSL certs for this verification using this system.

Re (2), let's please create a separate ticket from scratch, and not make any reference in that ticket to how things are implemented (because if the scenarios are satisfied, users just won't care).

**Comment by martinjoconnor** [comment]
Thanks, Graham.

This will work for the moment. I will generate the certificates in the morning and then test the recovery process.

Martin

**Comment by martinjoconnor** [comment]
Certificate process worked. Thanks. Closing this.
