### ISSUE TITLE
Controlled term fields behave badly in spreadsheet view

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#787]
Spreadsheet view is not handling controlled terms gracefully, especially if the selection is from a large branch. The drop-down arrow can freeze up the spreadsheet, terms don't appear quickly when typing begins, and UX interactions (key strokes, mouse clicks) are intermittent.

If more than one cell (of this controlled terms type) at a time is pasted, a large number of errors can appear on CEDAR, and BIoPortal can run slowly or even stop working, at least for a period. These errors may recover eventually, or may not.

**Comment by martinjoconnor** [comment]
While BioPortal's REST API can be slow when searching for terms in unindexed branches, an initial examination does indicate that many extraneous calls are being generated by CEDAR in some situations. Also, timeouts seems to be incorrect because field values are immediately indicated as invalid before a BioPortal call returns.

**Comment by willrett** [comment]
I have a fix for this, and will put it on staging.

**Comment by martinjoconnor** [comment]
Great. Will give it  a spin.

**Comment by martinjoconnor** [comment]
Quite a few front end improvements made, mainly relating to minimizing calls to BioPortal and caching results. 

Still a deeper issue with some large branches in BioPortal where the calls will timeout because ontology branches are not indexed (https://github.com/metadatacenter/cedar-terminology-server/issues/32)
