### ISSUE TITLE
Front end support for alternate questions

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#817]
e.g. for CDEs

Task https://github.com/metadatacenter/cedar-model-validation-library/issues/85 handles single question text support.  Multiple questions could be a quite a bit more complex.

Requires metadatacenter/cedar-model-validation-library#85

**Comment by martinjoconnor** [comment]
Task metadatacenter/cedar-model-validation-library#85 now handles preferred question text (single) and alternate questions (which may be multiple) at the model level. 

We also need to support alternate questions at the UI level.

**Comment by marcosmro** [comment]
This should include see, choose, and update alternate questions at the UI level.

**Comment by marcosmro** [comment]
The CEDAR model defines three fields that capture field label information. These fields are:
- `schema:name`. It stores the field name. (required)
- `skos:prefLabel`. It stores the field preferred label. (optional)
- `skos:altLabel`. It stores an array of alternate labels for the field. (optional)

If `skos:prefLabel` is null or empty, the UI will use `schema:name` as the field’s question text. Otherwise, the value of `skos:prefLabel` will be used as the question text.

I've completed the front end capabilities to select the preferred label from the list of available alternate labels, as well as to add/remove values from the array of alternate labels. Here are some notes about this feature:

1. When there are no alternate labels in the model (i.e., there is no value for the `skos:altLabel` field, or the field it’s empty), the "Enter preferred label" field behaves as a regular input text field. The user can enter a string that will act as the preferred label for the field. (see Screenshot 1)
2. When the model contains one or several alternate labels, the "Enter preferred label" field behaves as a selection field that allows the user to pick one of the alternate labels. In this case, the user can also decide to add his/her own preferred label by typing a new value into the field. (see Screenshots 2 and 3)
3. The Options tab contains now an "Enter Alternate Labels" field that makes it possible to add new alternate labels to the model, as well as to remove existing alternate labels from it. (see Screenshot 4)
4. Any updates done to the alternate labels are immediately reflected in the preferred label drop down.

Screenshot 1:
![Screen Shot 2020-08-03 at 3 40 10 PM](https://user-images.githubusercontent.com/7634440/89233937-9edcac80-d59f-11ea-9b59-277ef10d4799.png)

Screenshot 2:
![Screen Shot 2020-08-03 at 3 18 46 PM](https://user-images.githubusercontent.com/7634440/89233874-6b9a1d80-d59f-11ea-98be-be15c2a62f45.png)

Screenshot 3:
![Screen Shot 2020-08-03 at 3 18 51 PM](https://user-images.githubusercontent.com/7634440/89233879-6fc63b00-d59f-11ea-9500-d8f90e95bb47.png)

Screenshot 4:
![Screen Shot 2020-08-03 at 3 18 59 PM](https://user-images.githubusercontent.com/7634440/89233887-794fa300-d59f-11ea-8cbb-8c71ce3ba204.png)

**Comment by marcosmro** [comment]
Based on yesterday's meeting with the NCI, I've "locked" published fields so that only predefined question text (i.e., preferred label or alternate labels) can be used, not free text.
