### ISSUE TITLE
Write permitted after permission removed

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#846]
Create a folder and change the owner to be someone else while giving yourself read permission.  I can still write to this folder even though I do not have write permission.

**Comment by egyedia** [comment]
This behavior is the expected one since one of our last changes in the permission rules: if a node (folder or resource) is in a user's home folder (any level under that) that user has full access to the given node.
I double checked, if the folder is moved away (for instance to the top folder by the cedar-admin) just the new owner will have write permission to the folder
