### ISSUE TITLE
Versioning enhancements

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#867]
1.  Show draft version if it is not 0.0.1
2. Use a lock icon instead of globe.  Unfortunately, lock is already in use.
3. First publish gets a lecture.  Show a blurb about what publishing really means which says “Setting a document to published makes it persistent and cannot be undone.  
4. Make the default for publication closed in the filter panel.
5. Toggle latest on or off.  
6. Remove published, draft and all toggles.   
7. 50 (5 accessible) instance count.
80.  Populating a draft template, issue a warning. Otherwise people may lose their instance if the template changes.  
9. If you make a copy to create a new version you create a new version history. We’ll have to educate people about this. 
10. Use the word version or release instead of publication.    
11. f022 or  f044 for populate icon as needed. 
12. xsd:date : yyyy-MM-dd
13. folder icon color not black

**Comment by graybeal** [comment]
If it helps, here are the essentials and non-essentials as I see it. (And 9 is how things currently function, right? It's just the education part that needs doing.)

Essential: 
* 5 (which can be summarized as "2 views: `Latest` shows only draft and latest published; `Not Latest` shows everything")
* 6 (part of implementing 5)
* 1 (avoids a lot of noise/confusion in interface)

Strongly encourage : 
* 10  (so that people start out with an accurate idea)
* 11  (just picking a different, clearer icon)
* 2 (again looking for a clear icon for templates that can't be modified; could pick a different lock icon, I think there are a few)

Encourage to maximize acceptance: 
* 3 (good on-boarding)
* 4 (cleans up the UI a bit)
* 8 (avoids future confusion when a needed template goes away; probably this should include a warning when a draft template with instances is changed to published, too)
* 9 (just the education part, for good on-boarding)

I'd like 7, 12, and 13 very much but have to admit they are all non-essential for this change.
