### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#92]

**Comment by martinjoconnor** [comment]
Create policy and link to on login page.

**Comment by graybeal** [comment]
This Privacy Statement applies to Web sites and services that are operated by the Center for Expanded Data Annotation and Retrieval. The Center for Expanded Data Annotation and Retrieval is not responsible for the content or the privacy policies of sites to which it may link.

**Information Collected**

We offer a number of services that do not require you to register for an account or provide any personal information to us. In order to provide our full range of services, we may collect the following types of information:

Information you provide - When you become a registered user, we ask you for personal information (such as your name, email address and an account password). We also offer you the opportunity to customize your individual profile.
Cookies - When you visit the Center for Expanded Data Annotation and Retrieval web service, we send one or more cookies - a small file containing a string of characters - to your computer that uniquely identifies your browser. We use cookies to improve the quality of our service by storing user preferences and tracking user trends, such as how people search. Most browsers are initially set up to accept cookies, but you can reset your browser to refuse all cookies or to indicate when a cookie is being sent. However, some features and services of the Center for Expanded Data Annotation and Retrieval may not function properly if your cookies are disabled.
Log information - Our servers automatically record information that your browser sends whenever you visit a website. These server logs may include information such as your web request, Internet Protocol address, browser type, browser language, the date and time of your request and one or more cookies that may uniquely identify your browser.
Navigation commands - As you navigate our custom web application services, the Center for Expanded Data Annotation and Retrieval may collect information about your actions in order to understand and optimize the user experience offered by the web application services.
User communications - When you send email or other communication to the Center for Expanded Data Annotation and Retrieval, we may retain those communications in order to process your inquiries, respond to your requests and improve our services.
Embedded URLs - In order to provide maximum site utility, the Center for Expanded Data Annotation and Retrieval may also use a tracking technique that uses embedded URLs to allow use of the site without cookies. Embedded URLs manifest themselves as plain text or encoded extensions to the URL that appears in the browser address or location toolbar. This technology allows limited information to follow you as you navigate the site, but is not identified to personal data and is not used beyond the session. While this increases your ability to surf the site, it does not replace the functionality or streamlining of cookies and may limit your use of many convenience features offered by the site.

**Information Use**

We use information we collect for the following purposes:

- Auditing, research and analysis in order to maintain, protect and improve our services
- Providing our services to users, including the display of customized content
- Scientific research about the operation and usage of the web application services and their information artifacts
- Ensuring the technical functioning of our network

**Information Sharing**

The NCBO may share anonymized log data with collaborators for research purposes.

The Center for Expanded Data Annotation and Retrieval uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. 

**Data Security**

To prevent unauthorized access, maintain data accuracy, and ensure the appropriate use of information, we have put in place appropriate physical, electronic, and managerial procedures to protect the information we collect online.
