### ISSUE TITLE
Shared with Me and Shared with Everybody modes

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#943]
The current Shared with Me view shows every resource visible to a user via direct or group sharing. This also effectively shows all resources shared to the Everybody group - resulting in a very large set of resources being returned.

Suggest changing the current Shared with Me and adding Shared with Everybody as follows:

(1) The current Shared with Me view should not show resources shared via the Everybody group - only resources shared with that user directly or via 'non-Everybody' groups.

(2) Add a Shared with Everybody view that would allow users to see all shares, including shares via the Everybody group (current behaviour).

**Comment by gilliankerr** [comment]
I prefer suggestion 1 above, with the exception of a folder for CEDAR-Training resources. The training folder should include a couple of great examples eg MiARR. There are two problems with the current setup: 
- The 'Shared with me' view is cluttered and confusing, and interferes with the ability of a team to collaborate using shared spaces, and also,
- The search brings up hundreds of irrelevant findings, many of them half-finished, making it difficult to quickly narrow down on relevant fields and elements. Searches do not allow filtering by workspace, so we can't narrow down searches by our own projects. 
Suggestion 2 might solve the first problem but not the second.

**Comment by martinjoconnor** [comment]
(1) and (2) are both steps in the same suggestion. (I've reworded to clarify.)

**Comment by gilliankerr** [comment]
How would the search behaviour change? I just searched for 'diagnosis' within my own workspace and came up with about 2,400 items. Can I restrict search?

**Comment by martinjoconnor** [comment]
Search would not by default change. Modifying search to have both modes would be a different task - and would be complex because it would require the creation of additional search index.

**Comment by gilliankerr** [comment]
Right, makes sense. I'm now investigating SharePoint lists to manage our metadata as an alternative to CEDAR. CEDAR's functionality is great but the lack of training resources makes it hard to incorporate into our processes.

**Comment by graybeal** [comment]
Gillian, I think your last comment is a bit of topic for this ticket. Please contact me directly to discuss your concerns further — training resources are continually added, and could be added at an increased rate if it would have an impact on your situation.

**Comment by graybeal** [comment]
I don't think we've addressed your question about search. We definitely will be adding more refined search capabilities to CEDAR; the exact schedule for that, and targeted richness of the search capability, is a function of our funders. But I suspect that within 6 months we will have a search capability that can consider the owner or other descriptive metadata about the items. 

Regarding searching for "diagnosis", I'd first observe it's a very general term in a biomedical resources, so for sure winnowing is to be expected. As of today you can be more selective by any of the following:
(a) adding more terms using AND in between, to require all terms to be present,
(b) eliminating things that aren't of the right type using the type filter icons on the left side (you probably don't care about metadata, and maybe you only want elements or templates, not the other),
(c) make sure you have  chosen to view only published assets using the drop-down on the left,
(d) sort by creation or update time to find more recent things. 

Many of the things you are finding are likely CDE fields, and I know that searching for CDE fields can be hard for their users as well (since there are 50K or so of them). CDE template creators often use the source of the field (which group created it) as a way to winnow the options; we are likely to be adding that capability within the next 6 months also.

**Comment by gilliankerr** [comment]
Thanks, John
